# Generated by Django 5.2.8 on 2025-11-21 09:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sender_name",
                    models.CharField(
                        blank=True,
                        help_text="Name for anonymous submissions",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "sender_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email for anonymous submissions",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("general", "General Inquiry"),
                            ("proposal", "Project Proposal"),
                            ("job", "Job Opportunity"),
                            ("collaboration", "Collaboration"),
                            ("feedback", "Feedback"),
                            ("other", "Other"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField(help_text="Main message content")),
                (
                    "project_budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Budget for project proposals",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "project_timeline",
                    models.CharField(
                        blank=True,
                        help_text="Expected timeline for project",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "attachments",
                    models.JSONField(
                        blank=True, default=list, help_text="List of attachment URLs"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("read", "Read"),
                            ("in_progress", "In Progress"),
                            ("responded", "Responded"),
                            ("archived", "Archived"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.BooleanField(default=False, help_text="Mark as priority"),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes (only visible to admins)",
                        null=True,
                    ),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of sender", null=True
                    ),
                ),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "responded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responded_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        help_text="Authenticated user who sent the message (optional for anonymous contact forms)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageReply",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "is_internal",
                    models.BooleanField(
                        default=False,
                        help_text="Internal note not visible to message sender",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_replies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="contacts.contactmessage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Reply",
                "verbose_name_plural": "Message Replies",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="contactmessage",
            index=models.Index(
                fields=["sender", "-created_at"], name="contacts_co_sender__5092bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contactmessage",
            index=models.Index(fields=["status"], name="contacts_co_status_e4ac66_idx"),
        ),
        migrations.AddIndex(
            model_name="contactmessage",
            index=models.Index(
                fields=["message_type"], name="contacts_co_message_7ef18f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contactmessage",
            index=models.Index(
                fields=["-created_at"], name="contacts_co_created_c45a93_idx"
            ),
        ),
    ]
