# Generated by Django 5.1.3 on 2025-11-20 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="sender_email",
            field=models.EmailField(
                blank=True,
                help_text="Email for anonymous submissions",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="sender_name",
            field=models.CharField(
                blank=True,
                help_text="Name for anonymous submissions",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                help_text="Authenticated user who sent the message (optional for anonymous contact forms)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
