# Generated by Django 5.2.8 on 2025-11-21 09:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(help_text="Short description")),
                (
                    "long_description",
                    models.TextField(
                        blank=True, help_text="Detailed project description", null=True
                    ),
                ),
                (
                    "technologies",
                    models.JSONField(
                        default=list, help_text="List of technologies used"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        help_text="Your role in the project", max_length=100
                    ),
                ),
                (
                    "team_size",
                    models.PositiveIntegerField(
                        blank=True, help_text="Number of team members", null=True
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "current",
                    models.BooleanField(
                        default=False, help_text="Currently working on this"
                    ),
                ),
                (
                    "project_url",
                    models.URLField(
                        blank=True,
                        help_text="Live project URL",
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "github_url",
                    models.URLField(
                        blank=True,
                        help_text="GitHub repository URL",
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "demo_url",
                    models.URLField(
                        blank=True,
                        help_text="Demo or video URL",
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        help_text="Project demo video",
                        null=True,
                        upload_to="projects/videos/",
                    ),
                ),
                (
                    "highlights",
                    models.JSONField(
                        default=list, help_text="Key highlights or features"
                    ),
                ),
                (
                    "challenges",
                    models.TextField(
                        blank=True,
                        help_text="Challenges faced and solutions",
                        null=True,
                    ),
                ),
                (
                    "outcomes",
                    models.TextField(
                        blank=True, help_text="Results and impact", null=True
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(
                        default=False, help_text="Feature this project on profile"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["-featured", "-start_date", "order"],
            },
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.ImageField(upload_to="projects/")),
                ("caption", models.CharField(blank=True, max_length=200, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "uploaded_at"],
            },
        ),
    ]
