# Generated by Django 5.1.3 on 2025-11-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Project demo video",
                null=True,
                upload_to="projects/videos/",
            ),
        ),
    ]
