# Generated by Django 5.2.8 on 2025-11-19 19:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "institution",
                    models.CharField(
                        help_text="School or university name", max_length=200
                    ),
                ),
                (
                    "degree",
                    models.CharField(
                        help_text="Degree type (e.g., Bachelor's, Master's)",
                        max_length=200,
                    ),
                ),
                (
                    "field_of_study",
                    models.CharField(
                        help_text="Major or field of study", max_length=200
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "current",
                    models.BooleanField(default=False, help_text="Currently studying"),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True, help_text="GPA or grade", max_length=50, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "activities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Extracurricular activities",
                        null=True,
                    ),
                ),
                (
                    "achievements",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Academic achievements or honors",
                        null=True,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Education",
                "verbose_name_plural": "Education",
                "ordering": ["-start_date", "order"],
            },
        ),
    ]
