# Generated by Django 5.2.8 on 2025-11-19 19:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Certification name", max_length=200),
                ),
                (
                    "issuer",
                    models.CharField(help_text="Issuing organization", max_length=200),
                ),
                ("issue_date", models.DateField()),
                (
                    "expiration_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank if certification doesn't expire",
                        null=True,
                    ),
                ),
                (
                    "credential_id",
                    models.CharField(
                        blank=True,
                        help_text="Certification ID or credential number",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "credential_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to verify certification",
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "skills",
                    models.JSONField(
                        default=list,
                        help_text="Skills demonstrated by this certification",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certification",
                "verbose_name_plural": "Certifications",
                "ordering": ["-issue_date", "order"],
            },
        ),
    ]
